version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "No actual build needed for static HTML"
  post_build:
    commands:
      - echo "Build completed successfully on $(date)"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*
